In [1]:
import numpy as np
import pandas as pd
# making a Dataframe from dictionary
students = {
    "name": ['Maya','Ankita','Preet','Maryam','Sahil','Jaishwal'],
    "age": [23,55,64,32,20,16],
    "MaxEducation": ['Bachelor','PHD','PHD','Masters','Undergrad','Intermediate'],
    "course": ['BSCS','Maths','English','Economics','BBA','ICS'],
    "Institute": ['Muhammad Ali Jinnah University','IBA','IBA','King Saud University','Habib University','Bahria College'],
    "email": ['Maya.edu@gmail.com','Ankita.edu@gmail.com','Preet.edu@gmail.com','Maryam.edu@gmail.com','Sahil.edu@gmail.com','Jaishwal.edu@gmail.com']}
students

studentInfo = pd.DataFrame(students)
studentInfo

,name,age,MaxEducation,course,Institute,email
0,Maya,23,Bachelor,BSCS,Muhammad Ali Jinnah University,Maya.edu@gmail.com
1,Ankita,55,PHD,Maths,IBA,Ankita.edu@gmail.com
2,Preet,64,PHD,English,IBA,Preet.edu@gmail.com
3,Maryam,32,Masters,Economics,King Saud University,Maryam.edu@gmail.com
4,Sahil,20,Undergrad,BBA,Habib University,Sahil.edu@gmail.com
5,Jaishwal,16,Intermediate,ICS,Bahria College,Jaishwal.edu@gmail.com

In [2]:
studentInfo.index = [102134232011,102134232012,102134232013,102134232014,102134232015,102134232016]
studentInfo

,name,age,MaxEducation,course,Institute,email
102134232011,Maya,23,Bachelor,BSCS,Muhammad Ali Jinnah University,Maya.edu@gmail.com
102134232012,Ankita,55,PHD,Maths,IBA,Ankita.edu@gmail.com
102134232013,Preet,64,PHD,English,IBA,Preet.edu@gmail.com
102134232014,Maryam,32,Masters,Economics,King Saud University,Maryam.edu@gmail.com
102134232015,Sahil,20,Undergrad,BBA,Habib University,Sahil.edu@gmail.com
102134232016,Jaishwal,16,Intermediate,ICS,Bahria College,Jaishwal.edu@gmail.com

In [3]:
# agar ye method use krengy tw sabko change krna hoga
# column name changing method 1
studentInfo.columns = [
    "Name",
    "Age",
    "MaxEducation",
    "Course",
    "Institute",
    "Email"
]
studentInfo

,Name,Age,MaxEducation,Course,Institute,Email
102134232011,Maya,23,Bachelor,BSCS,Muhammad Ali Jinnah University,Maya.edu@gmail.com
102134232012,Ankita,55,PHD,Maths,IBA,Ankita.edu@gmail.com
102134232013,Preet,64,PHD,English,IBA,Preet.edu@gmail.com
102134232014,Maryam,32,Masters,Economics,King Saud University,Maryam.edu@gmail.com
102134232015,Sahil,20,Undergrad,BBA,Habib University,Sahil.edu@gmail.com
102134232016,Jaishwal,16,Intermediate,ICS,Bahria College,Jaishwal.edu@gmail.com

In [4]:
# column name renaming method 2
studentInfo.rename(columns={
    "MaxEducation": "Higher Education",
    "Course": "Degree"}, inplace = True)

In [5]:
studentInfo

,Name,Age,Higher Education,Degree,Institute,Email
102134232011,Maya,23,Bachelor,BSCS,Muhammad Ali Jinnah University,Maya.edu@gmail.com
102134232012,Ankita,55,PHD,Maths,IBA,Ankita.edu@gmail.com
102134232013,Preet,64,PHD,English,IBA,Preet.edu@gmail.com
102134232014,Maryam,32,Masters,Economics,King Saud University,Maryam.edu@gmail.com
102134232015,Sahil,20,Undergrad,BBA,Habib University,Sahil.edu@gmail.com
102134232016,Jaishwal,16,Intermediate,ICS,Bahria College,Jaishwal.edu@gmail.com

In [6]:
# adding a column
studentInfo["CGPA"]=[3.4,2.6,3.8,4.0,2.9,3.0]

In [7]:
studentInfo

,Name,Age,Higher Education,Degree,Institute,Email,CGPA
102134232011,Maya,23,Bachelor,BSCS,Muhammad Ali Jinnah University,Maya.edu@gmail.com,3.4
102134232012,Ankita,55,PHD,Maths,IBA,Ankita.edu@gmail.com,2.6
102134232013,Preet,64,PHD,English,IBA,Preet.edu@gmail.com,3.8
102134232014,Maryam,32,Masters,Economics,King Saud University,Maryam.edu@gmail.com,4.0
102134232015,Sahil,20,Undergrad,BBA,Habib University,Sahil.edu@gmail.com,2.9
102134232016,Jaishwal,16,Intermediate,ICS,Bahria College,Jaishwal.edu@gmail.com,3.0

In [8]:
# Assigning a value by checking column
studentInfo["Adult"] = studentInfo["Age"]>=18
studentInfo

,Name,Age,Higher Education,Degree,Institute,Email,CGPA,Adult
102134232011,Maya,23,Bachelor,BSCS,Muhammad Ali Jinnah University,Maya.edu@gmail.com,3.4,True
102134232012,Ankita,55,PHD,Maths,IBA,Ankita.edu@gmail.com,2.6,True
102134232013,Preet,64,PHD,English,IBA,Preet.edu@gmail.com,3.8,True
102134232014,Maryam,32,Masters,Economics,King Saud University,Maryam.edu@gmail.com,4.0,True
102134232015,Sahil,20,Undergrad,BBA,Habib University,Sahil.edu@gmail.com,2.9,True
102134232016,Jaishwal,16,Intermediate,ICS,Bahria College,Jaishwal.edu@gmail.com,3.0,False

In [9]:
# Adding same value to every column
studentInfo["Country"] = "Pakistan"
studentInfo

,Name,Age,Higher Education,Degree,Institute,Email,CGPA,Adult,Country
102134232011,Maya,23,Bachelor,BSCS,Muhammad Ali Jinnah University,Maya.edu@gmail.com,3.4,True,Pakistan
102134232012,Ankita,55,PHD,Maths,IBA,Ankita.edu@gmail.com,2.6,True,Pakistan
102134232013,Preet,64,PHD,English,IBA,Preet.edu@gmail.com,3.8,True,Pakistan
102134232014,Maryam,32,Masters,Economics,King Saud University,Maryam.edu@gmail.com,4.0,True,Pakistan
102134232015,Sahil,20,Undergrad,BBA,Habib University,Sahil.edu@gmail.com,2.9,True,Pakistan
102134232016,Jaishwal,16,Intermediate,ICS,Bahria College,Jaishwal.edu@gmail.com,3.0,False,Pakistan

In [10]:
studentInfo.index = [1,2,3,4,5,6]
studentInfo

,Name,Age,Higher Education,Degree,Institute,Email,CGPA,Adult,Country
1,Maya,23,Bachelor,BSCS,Muhammad Ali Jinnah University,Maya.edu@gmail.com,3.4,True,Pakistan
2,Ankita,55,PHD,Maths,IBA,Ankita.edu@gmail.com,2.6,True,Pakistan
3,Preet,64,PHD,English,IBA,Preet.edu@gmail.com,3.8,True,Pakistan
4,Maryam,32,Masters,Economics,King Saud University,Maryam.edu@gmail.com,4.0,True,Pakistan
5,Sahil,20,Undergrad,BBA,Habib University,Sahil.edu@gmail.com,2.9,True,Pakistan
6,Jaishwal,16,Intermediate,ICS,Bahria College,Jaishwal.edu@gmail.com,3.0,False,Pakistan

In [11]:
# Assigning column at a specific location
studentInfo.insert(2,"Gender",["Female","Female","Female","Female","Male","Male",])
studentInfo

,Name,Age,Gender,Higher Education,Degree,Institute,Email,CGPA,Adult,Country
1,Maya,23,Female,Bachelor,BSCS,Muhammad Ali Jinnah University,Maya.edu@gmail.com,3.4,True,Pakistan
2,Ankita,55,Female,PHD,Maths,IBA,Ankita.edu@gmail.com,2.6,True,Pakistan
3,Preet,64,Female,PHD,English,IBA,Preet.edu@gmail.com,3.8,True,Pakistan
4,Maryam,32,Female,Masters,Economics,King Saud University,Maryam.edu@gmail.com,4.0,True,Pakistan
5,Sahil,20,Male,Undergrad,BBA,Habib University,Sahil.edu@gmail.com,2.9,True,Pakistan
6,Jaishwal,16,Male,Intermediate,ICS,Bahria College,Jaishwal.edu@gmail.com,3.0,False,Pakistan

In [12]:
# adding a row
studentInfo.loc[7] = [
    "Arohi",22,"Female","Undergrad","BSIT","IOBM","Arohi.edu.pk@gmail.com",3.5,22>=18,"Pakistan"]

In [13]:
studentInfo

,Name,Age,Gender,Higher Education,Degree,Institute,Email,CGPA,Adult,Country
1,Maya,23,Female,Bachelor,BSCS,Muhammad Ali Jinnah University,Maya.edu@gmail.com,3.4,True,Pakistan
2,Ankita,55,Female,PHD,Maths,IBA,Ankita.edu@gmail.com,2.6,True,Pakistan
3,Preet,64,Female,PHD,English,IBA,Preet.edu@gmail.com,3.8,True,Pakistan
4,Maryam,32,Female,Masters,Economics,King Saud University,Maryam.edu@gmail.com,4.0,True,Pakistan
5,Sahil,20,Male,Undergrad,BBA,Habib University,Sahil.edu@gmail.com,2.9,True,Pakistan
6,Jaishwal,16,Male,Intermediate,ICS,Bahria College,Jaishwal.edu@gmail.com,3.0,False,Pakistan
7,Arohi,22,Female,Undergrad,BSIT,IOBM,Arohi.edu.pk@gmail.com,3.5,True,Pakistan

In [14]:
# adding a row next to preet
new_row = pd.DataFrame([["Mubeen",14,"male","matric","Bio-Science","Aga Khan School","Mubeen.edu.pk@gmail.com",3.9,14>=18,"Pakistan"]],
                       columns = studentInfo.columns,
                       index=[5])
studentInfo = pd.concat([
    studentInfo.iloc[:3],
    new_row,
    studentInfo.iloc[3:]])

In [16]:
studentInfo

,Name,Age,Gender,Higher Education,Degree,Institute,Email,CGPA,Adult,Country
1,Maya,23,Female,Bachelor,BSCS,Muhammad Ali Jinnah University,Maya.edu@gmail.com,3.4,True,Pakistan
2,Ankita,55,Female,PHD,Maths,IBA,Ankita.edu@gmail.com,2.6,True,Pakistan
3,Preet,64,Female,PHD,English,IBA,Preet.edu@gmail.com,3.8,True,Pakistan
5,Mubeen,14,male,matric,Bio-Science,Aga Khan School,Mubeen.edu.pk@gmail.com,3.9,False,Pakistan
4,Maryam,32,Female,Masters,Economics,King Saud University,Maryam.edu@gmail.com,4.0,True,Pakistan
5,Sahil,20,Male,Undergrad,BBA,Habib University,Sahil.edu@gmail.com,2.9,True,Pakistan
6,Jaishwal,16,Male,Intermediate,ICS,Bahria College,Jaishwal.edu@gmail.com,3.0,False,Pakistan
7,Arohi,22,Female,Undergrad,BSIT,IOBM,Arohi.edu.pk@gmail.com,3.5,True,Pakistan

In [17]:
# the index gets incremented by 1
studentInfo.index += 1

In [18]:
studentInfo

,Name,Age,Gender,Higher Education,Degree,Institute,Email,CGPA,Adult,Country
2,Maya,23,Female,Bachelor,BSCS,Muhammad Ali Jinnah University,Maya.edu@gmail.com,3.4,True,Pakistan
3,Ankita,55,Female,PHD,Maths,IBA,Ankita.edu@gmail.com,2.6,True,Pakistan
4,Preet,64,Female,PHD,English,IBA,Preet.edu@gmail.com,3.8,True,Pakistan
6,Mubeen,14,male,matric,Bio-Science,Aga Khan School,Mubeen.edu.pk@gmail.com,3.9,False,Pakistan
5,Maryam,32,Female,Masters,Economics,King Saud University,Maryam.edu@gmail.com,4.0,True,Pakistan
6,Sahil,20,Male,Undergrad,BBA,Habib University,Sahil.edu@gmail.com,2.9,True,Pakistan
7,Jaishwal,16,Male,Intermediate,ICS,Bahria College,Jaishwal.edu@gmail.com,3.0,False,Pakistan
8,Arohi,22,Female,Undergrad,BSIT,IOBM,Arohi.edu.pk@gmail.com,3.5,True,Pakistan

In [22]:
# resetting the index
studentInfo = studentInfo.reset_index(drop=True)

In [23]:
studentInfo.index += 1

In [24]:
studentInfo

,Name,Age,Gender,Higher Education,Degree,Institute,Email,CGPA,Adult,Country
1,Maya,23,Female,Bachelor,BSCS,Muhammad Ali Jinnah University,Maya.edu@gmail.com,3.4,True,Pakistan
2,Ankita,55,Female,PHD,Maths,IBA,Ankita.edu@gmail.com,2.6,True,Pakistan
3,Preet,64,Female,PHD,English,IBA,Preet.edu@gmail.com,3.8,True,Pakistan
4,Mubeen,14,male,matric,Bio-Science,Aga Khan School,Mubeen.edu.pk@gmail.com,3.9,False,Pakistan
5,Maryam,32,Female,Masters,Economics,King Saud University,Maryam.edu@gmail.com,4.0,True,Pakistan
6,Sahil,20,Male,Undergrad,BBA,Habib University,Sahil.edu@gmail.com,2.9,True,Pakistan
7,Jaishwal,16,Male,Intermediate,ICS,Bahria College,Jaishwal.edu@gmail.com,3.0,False,Pakistan
8,Arohi,22,Female,Undergrad,BSIT,IOBM,Arohi.edu.pk@gmail.com,3.5,True,Pakistan

In [28]:
# using for loop through iterrows
for index,row in studentInfo.iterrows():
    print(f'{row['Name']} is {row['Age']} years old and she is doing her {row['Higher Education']} in {row['Degree']}.')

Maya is 23 years old and she is doing her Bachelor in BSCS.
Ankita is 55 years old and she is doing her PHD in Maths.
Preet is 64 years old and she is doing her PHD in English.
Mubeen is 14 years old and she is doing her matric in Bio-Science.
Maryam is 32 years old and she is doing her Masters in Economics.
Sahil is 20 years old and she is doing her Undergrad in BBA.
Jaishwal is 16 years old and she is doing her Intermediate in ICS.
Arohi is 22 years old and she is doing her Undergrad in BSIT.

In [ ]:
# using for loop through itertuples
for row in studentInfo.itertuples():
    print(f'My name is ')

In [ ]:
import numpy as np
age = np.array([12,33,44,55])
name = np.array(["maya","tina","aleena","preet"])
# np.nditer() does not accept two separate arguments like this.
for i,k in np.nditer(name,age):
    print(f'My name is {i} and my age is {k}.')

In [ ]:
import numpy as np
age = np.array([12,33,44,55])
name = np.array(["maya","tina","aleena","preet"])
# np.nditer() does not accept two separate arguments like this.
for i,k in zip(name,age):
    print(f'My name is {i} and my age is {k}.')

In [ ]:
import numpy as np

# Create NumPy array
name = np.array(["maya", "tina", "aleena", "preet"])

# Iterate through 1 array
for i in np.nditer(name):
    print(f"My name is {i}")